apiVersion: apps/v1
kind: Deployment
metadata:
  name: electronics-deployment
  labels:
    app: electronics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: electronics
  template:
    metadata:
      labels:
        app: electronics
    spec:
      containers:
      - name: electronics
        image: 992382539141.dkr.ecr.us-east-1.amazonaws.com/shopping-site-electronics:c0a216a8761ba071ba3a7766c90b005c9253ae31
        ports:
        - containerPort: 80
